language: node_js

node_js:
  - 8.9.4

cache:
  directories:
    - node_modules

script:
  # run these 2 targets in parallel jobs
  - make -jobs 2 travis_fast_checks travis_slow_checks

after_script:
  - codecov
