language: node_js

node_js:
  - 8.9.4

notifications:
    webhooks: https://www.travisbuddy.com/
    on_success: never

cache:
  directory:
    - studio-frontend/node_modules/

script:
  - make package-lock.validate
  - make i18n.pre_validate
  - npm run lint
  - npm run test

after_script:
  - codecov
