language: node_js

node_js:
  - 8.9.4

sudo: required
services:
 - docker

before_script:
 - docker build -t studio-frontend --no-cache .

script:
  - npm run lint
  - npm run test
  - make i18n.pre_validate
  - make package-lock.validate

after_script:
  - codecov
