language: node_js

node_js:
  - 8.9.4

cache:
  directories:
    - node_modules

env:
  global:
    - MAKEFLAGS="-j 2"

script:
  - make travis_fast_checks
  - make travis_slow_tests

after_script:
  - codecov
